#!/bin/sh

cd /tmp/
mkdir FirefoxInstalerCache/
cd FirefoxInstalerCache/
echo "Cache folder created"

wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/89.0.1/linux-x86_64/en-US/firefox-89.0.1.tar.bz2
tar -xjvf firefox-89.0.1.tar.bz2
echo "Firefox binary downloaded and unzipped"

git clone https://github.com/Can202/FirefoxInstallerLinux
echo "media cloned!"

sudo cp -R firefox/ /opt/
sudo cp FirefoxInstallerLinux/media/firefox-a /usr/bin/
sudo cp FirefoxInstallerLinux/media/firefox-a.desktop /usr/share/applications/

