#!/bin/sh

VERSIONFIREFOX=$(curl https://raw.githubusercontent.com/Can202/FirefoxInstallerLinux/develop/versions/firefox)
ARCHT="i686"

clear
if [ -f "/usr/games/lolcat" ] | [ -f "/usr/bin/lolcat" ]
then
    echo "
                  NN            
                WNXXNW          
     W         NXXXXXXNW         _____  _              __             
   NOkWWXK    NKKKXXXXXXNWW     |  ___|(_) _ __  ___  / _|  ___ __  __
  OdxxOkkON0kxooodk0KKKXKXNN    | |_   | || '__|/ _ \| |_  / _ \\ \/ /
 kddddxxxkkdolccccldk0KKKKKKX   |  _|  | || |  |  __/|  _|| (_) |>  < 
XooodkOOOOOOOOdcccclOK00000KKN  |_|    |_||_|   \___||_|   \___//_/\_\ 
OllooodkOdolllclccc:c00OOO0K0X                                        
Olllloodo,;:::ccc::;:OOkkO00OX   ___              _          _  _     
Nccclllloc,,;;;;;;,;oxxxkOOkOW  |_ _| _ __   ___ | |_  __ _ | || |  ___  _ __ 
 K:ccccllll:;;;;;:cooddxxxdxN    | | | '_ \ / __|| __|/ _  || || | / _ \| '__|
  Xc;:ccccclllllllllloooolxN     | | | | | |\__ \| |_| (_| || || ||  __/| |   
   WOc;;:ccccccccccccc::l0      |___||_| |_||___/ \__|\__,_||_||_| \___||_|   
      Kxl;;;;;;:;;;;;lxX        
         WOdl:;;:ldOW           


                                     by Can202  
" | lolcat
else
    echo "
                  NN            
                WNXXNW          
     W         NXXXXXXNW         _____  _              __             
   NOkWWXK    NKKKXXXXXXNWW     |  ___|(_) _ __  ___  / _|  ___ __  __
  OdxxOkkON0kxooodk0KKKXKXNN    | |_   | || '__|/ _ \| |_  / _ \\ \/ /
 kddddxxxkkdolccccldk0KKKKKKX   |  _|  | || |  |  __/|  _|| (_) |>  < 
XooodkOOOOOOOOdcccclOK00000KKN  |_|    |_||_|   \___||_|   \___//_/\_\ 
OllooodkOdolllclccc:c00OOO0K0X                                        
Olllloodo,;:::ccc::;:OOkkO00OX   ___              _          _  _     
Nccclllloc,,;;;;;;,;oxxxkOOkOW  |_ _| _ __   ___ | |_  __ _ | || |  ___  _ __ 
 K:ccccllll:;;;;;:cooddxxxdxN    | | | '_ \ / __|| __|/ _  || || | / _ \| '__|
  Xc;:ccccclllllllllloooolxN     | | | | | |\__ \| |_| (_| || || ||  __/| |   
   WOc;;:ccccccccccccc::l0      |___||_| |_||___/ \__|\__,_||_||_| \___||_|   
      Kxl;;;;;;:;;;;;lxX        
         WOdl:;;:ldOW           


                                     by Can202
"
fi

depen=true

echo "checking dependencies..."
if [ ! -f "/usr/bin/git" ]
then
    echo git is not installed...
    depen=false
    read nothing
fi
if [ ! -f "/usr/bin/curl" ]
then
    echo curl is not installed...
    depen=false
    read nothing
fi
if [ ! -f "/usr/bin/tar" ]
then
    echo tar is not installed...
    depen=false
    read nothing
fi

if [ $depen = "false" ]
then
    exit
fi

cd /tmp/


# removing cache
if [ -d "/tmp/FirefoxInstalerCache/" ]
then
    rm -R FirefoxInstalerCache/
fi


mkdir FirefoxInstalerCache/
cd FirefoxInstalerCache/
echo "Cache folder created"

curl -O https://download-installer.cdn.mozilla.net/pub/firefox/releases/$VERSIONFIREFOX/linux-$ARCHT/en-US/firefox-$VERSIONFIREFOX.tar.bz2
tar -xjvf firefox-$VERSIONFIREFOX.tar.bz2
echo "Firefox binary downloaded and unzipped"

git clone https://github.com/Can202/FirefoxInstallerLinux
cd FirefoxInstallerLinux/
git checkout v0.9
cd ../
echo "media cloned!"

sed -i 's/userh/'$USER'/g' FirefoxInstallerLinux/media/firefox-can.desktop
sed -i 's/userh/'$USER'/g' FirefoxInstallerLinux/media/firefox-can


cp -R firefox/ /home/$USER/.firefox-can
chmod a+x FirefoxInstallerLinux/media/firefox-can
cp FirefoxInstallerLinux/media/firefox-can.desktop /home/$USER/.local/share/applications/
cp FirefoxInstallerLinux/media/firefox-can /home/$USER/.firefox-can/
echo "firefox installed"

cd ../
rm -R FirefoxInstalerCache/
echo "chache removed!"

