#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Firefox ESR? (enter to continue)"
    read nothing
    rm -R /home/userh/.firefox-esr-can/
    rm /home/userh/.local/share/applications/firefox-esr-can.desktop
    
    echo "removed"
    exit
fi

if [ $1 = "do" ]
then
    /home/userh/.firefox-esr-can/firefox $2 $3 $4 $5 $6 $7 $8 $9
else
    /home/userh/.firefox-esr-can/firefox
fi


