#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Palemoon? (enter to continue)"
    read nothing
    rm -R /home/userh/.palemoon-can/
    rm /home/userh/.local/share/applications/palemoon-can.desktop
    
    echo "removed"
    exit
fi

if [ $1 = "do" ]
then
    /home/userh/.palemoon-can/palemoon $2 $3 $4 $5 $6 $7 $8 $9
else
    /home/userh/.palemoon-can/palemoon
fi


