#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Firefox? (enter to continue)"
    read nothing
    sudo rm -R /opt/firefox/
    sudo rm /usr/bin/firefox-can
    sudo rm /usr/share/applications/firefox-can.desktop
    exit
fi

/opt/firefox/firefox

