#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Firefox? (enter to continue)"
    read nothing
    rm -R /home/userh/.firefox-can/
    rm /home/userh/.local/share/applications/firefox-can.desktop
    echo "removed"
    exit
fi

if [ $1 = "--help" ]
then
    clear
    echo "Commands"
    echo "--help     		see available commands"
    echo "--remove		remove firefox"
    echo "do [command]		send a firefox command"
    echo "do --help		see firefox commands"
    exit
fi

if [ $1 = "do" ]
then
    /home/userh/.firefox-can/firefox $2 $3 $4 $5 $6 $7 $8 $9
else
    /home/userh/.firefox-can/firefox
fi


