#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Firefox? (enter to continue)"
    read nothing
    sudo rm -R /opt/firefox/
    sudo rm /usr/bin/firefox-can
    sudo rm /usr/share/applications/firefox-can.desktop
    exit
fi

if [ $1 = "--help" ]
then
    clear
    echo "COMANDS"
    echo "--help     		see available commands"
    echo "--remove		remove firefox"
    echo "do [command]		send a firefox command"
    echo "do --help		see firefox commands"
    exit
fi

if [ $1 = "do" ]
then
    /opt/firefox/firefox $2 $3 $4 $5 $6 $7 $8 $9
else
    /opt/firefox/firefox
fi


