#!/bin/sh

cd /tmp/
sudo rm -R FirefoxInstalerCache/
mkdir FirefoxInstalerCache/
cd FirefoxInstalerCache/
echo "Cache folder created"

wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/89.0.1/linux-x86_64/en-US/firefox-89.0.1.tar.bz2
tar -xjvf firefox-89.0.1.tar.bz2
echo "Firefox binary downloaded and unzipped"

git clone https://github.com/Can202/FirefoxInstallerLinux
cd FirefoxInstallerLinux/
git checkout v0.2
cd ../
echo "media cloned!"

sudo cp -R firefox/ /opt/
chmod a+x FirefoxInstallerLinux/media/firefox-can
sudo cp FirefoxInstallerLinux/media/firefox-can /usr/bin/
sudo cp FirefoxInstallerLinux/media/firefox-can.desktop /usr/share/applications/
echo "firefox installed"

cd ../
sudo rm -R FirefoxInstalerCache/
echo "chache removed!"

