#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Seamonkey? (enter to continue)"
    read nothing
    rm -R /home/userh/.seamonkey-can/
    rm /home/userh/.local/share/applications/seamonkey-can.desktop
    echo "removed"
    exit
fi

if [ $1 = "do" ]
then
    /home/userh/.seamonkey-can/seamonkey $2 $3 $4 $5 $6 $7 $8 $9
else
    /home/userh/.seamonkey-can/seamonkey
fi


