#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Thunderbird? (enter to continue)"
    read nothing
    rm -R /home/userh/.thunderbird-can/
    rm /home/userh/.local/share/applications/thunderbird-can.desktop
    
    echo "removed"
    exit
fi

if [ $1 = "do" ]
then
    /home/userh/.thunderbird-can/thunderbird $2 $3 $4 $5 $6 $7 $8 $9
else
    /home/userh/.thunderbird-can/thunderbird
fi


