#!/bin/sh

if [ $1 = "--remove" ]
then
    echo "are you sure that you want to remove Waterfox? (enter to continue)"
    read nothing
    rm -R /home/userh/.waterfox-can/
    rm /home/userh/.local/share/applications/waterfox-can.desktop
    
    echo "removed"
    exit
fi

if [ $1 = "do" ]
then
    /home/userh/.waterfox-can/waterfox $2 $3 $4 $5 $6 $7 $8 $9
else
    /home/userh/.waterfox-can/waterfox
fi


